name: CI/CD Pipeline with Security Scans

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  security-scan:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js (or your runtime)
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run security scan with npm audit
      run: npm audit --audit-level=high

    - name: Run static code analysis with ESLint (optional)
      run: |
        npm install eslint
        npx eslint .

  deploy:
    name: Deploy App
    runs-on: ubuntu-latest
    needs: security-scan

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Deploy to Vercel (or Heroku, etc.)
      run: echo "Deploy step here"
      # Replace with your actual deployment script or action
